name: Build and Deploy
on:
  push:	
    branches:	
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true 

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Dependencies
      run: |
        npm config set registry https://registry.npmjs.org/
        rm -rf package-lock.json node_modules
        npm install

    - name: Build Hexo
      run: ./node_modules/hexo/bin/hexo generate

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.HEXO_TOKEN }}
        publish_dir: ./public
        publish_branch: gh-pages