name: Build and Deploy
on:
  push:	
    branches:	
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true 

    - name: Build and Deploy
      uses: renzhaosy/hexo-deploy-action@master
      with:
        deploy-key: ${{ secrets.HEXO_TOKEN }}
        commit-msg: ${{ github.event.head_commit.message }}
        user-name: ${{ github.event.head_commit.author.name }}
        user-email: ${{ github.event.head_commit.author.email }}